### PR TITLE
updated application flow diagram on server side

### PR DESCRIPTION
**Pull request by olivetreezhao**

### CODE REVIEW

**Review by hpollittsmith — CHANGES_REQUESTED** [review]
Just a few comments/suggestions:

- "Initialization" is mis-spelled in the System Initialization block
- Do you explain what App_Tick is/does? Otherwise, the purpose of this block is not clear
- The flow of the blue arrow is not really clear
- "CMD?" is not clear--is this checking if a command has been received from the client?

**Comment by olivetreezhao** [comment]
the diagram is updated according to your input. please review.

**Review by hpollittsmith — CHANGES_REQUESTED** [review]
Does the App_Tick box do anything? Does it need to be there, or can the flow go straight into the Connected? box? If App_Tick box does something, then you should replace App_Tick with what the program does, as App_Tick is not meaningful to the diagram.

I would also replace CMD with Command, as it is the only abbreviation in the diagram.

**Comment by olivetreezhao** [comment]
The App_Tick box is to indicate where user application goes, which is the application structure arrangement recommended by ST to use their BLE stack. My original version brought in some mis-leading as this box is not a step in the logic, but suppose to be a grouping box to indicate where these functions belong to in the application. I just updated the diagram. Please review to see if it is clear to serve the purpose stated above.

Thanks,
Olive

**Review by hpollittsmith — CHANGES_REQUESTED** [review]
Almost there! Can you increase the App_Tick box to include the blue loop? I assume that's part of App_Tick. Also, can you add some extra blue arrows to make the flow quite clear? For example, a blue arrowhead coming out of the"Put BlueNRG into discoverable mode" box, and one coming out of the "Transmit data, reset heart beat..." box, and out of the "Put BlueNRG into sleep and start heartbeat timer" box. Just to make the program flow very clear.

Also, I believe "heart beat" should be one word "heartbeat".

**Comment by olivetreezhao** [comment]
The blue loop is not included in the App_Tick. It is the big while(1) loop in main() to keep the server running. I have renamed it to “main loop” to tell it from “App_Tick user application”. The Lucid chart does not allow me to add more arrows to the two long blue loop lines as they are connected from one block to another and have arrows already when reach the second block.

**Comment by olivetreezhao** [comment]
Ok, I added extra arrows to the blue lines in ppt. new diagram is uploaded.
Olive

**Review by hpollittsmith — APPROVED** [review]

**Pull request merged**
